name: e2e

on:
  pull_request:
  repository_dispatch:
    types: [core_pr]

jobs:
  e2e-test:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup core
        run: |
          cd ..
          git clone https://github.com/flux3dp/beam-studio-core.git
          cd beam-studio-core
          yarn install
      - name: Setup web
        run: |
          yarn install
      - name: Run e2e tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          start: yarn start
          wait-on: 'http://localhost:8080'
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          name: dev
