name: e2e

on:
  pull_request:
  workflow_dispatch:
    inputs:
      core_branch:
        description: "Core Branch"
        required: false
        default: "master"

jobs:
  e2e-test:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Beam Studio Core
        uses: actions/checkout@v3
        with:
          repository: flux3dp/beam-studio-core
          ref: ${{ github.event.inputs.core_branch }}
          path: .github/actions/beam-studio-core
      - name: Copy Beam Studio Core
        run: |
          cp -R .github/actions/beam-studio-core ../beam-studio-core
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.19
      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          # Disable running of tests within install job
          runTests: false
          build: yarn install
      - name: Setup web and run e2e tests
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_username: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          record: true
          group: "Actions example"
          browser: chrome
          install: false
          parallel: true
          start: yarn start
          wait-on: "http://localhost:8080"
          wait-on-timeout: 120
