name: ready-for-deployment

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [core_merged]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup core
        run: |
          cd ..
          git clone https://github.com/flux3dp/beam-studio-core.git
          cd beam-studio-core
          yarn install
      - name: Setup web
        run: |
          yarn install
      - name: Build artifact
        run: |
          yarn run build
      - name: Deployment via scp
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist
          remote: /var/www/beam-studio-web
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
  post-deployment-test:
    needs: deployment
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - uses: actions/checkout@v2
      - name: Run e2e test against the production environment
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_username: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          group: 'Group'
          config-file: cypress.prod.json
          record: true
          parallel: true
          browser: chrome
          start: |
            yarn install
