name: ready-for-deployment

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [core_merged]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup core
        run: |
          cd ..
          git clone https://github.com/flux3dp/beam-studio-core.git
          cd beam-studio-core
          yarn install
      - name: Setup web
        run: |
          yarn install
      - name: Run e2e tests
        run: |
          yarn run cy:test
      - name: Build artifact
        run: |
          yarn run build
      - name: Archive production artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          retention-days: 7
          path: |
            dist
  deployment:
    needs: e2e-test
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Deployment via scp
        uses: garygrossgarten/github-action-scp@release
        with:
          local: "."
          remote: /var/www/beam-studio-web
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
