name: ready-for-deployment

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [core_merged]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup core
        run: |
          cd ..
          git clone https://github.com/flux3dp/beam-studio-core.git
          cd beam-studio-core
          yarn install
      - name: Setup web
        run: |
          yarn install
      - name: Build artifact
        run: |
          yarn run build
      - name: Deployment via scp
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist
          remote: /var/www/beam-studio-web
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
  post-deployment-test:
    needs: deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run e2e test against the production environment
        run: |
          yarn install
          yarn run cy:prod
