name: ready-for-deployment

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup core
        run: |
          cd ..
          git clone https://github.com/flux3dp/beam-studio-core.git
          cd beam-studio-core
          yarn install
      - name: Setup web
        run: |
          yarn install
      - name: Run e2e tests
        run: |
          yarn run cy:test
  deployment:
    needs: e2e-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build dist
        run: |
          yarn run build
          ls
    - name: Copy files to linode via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "./dist/*"
        target: "/var/www/beam-studio-web"

